cymbalcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('main_app.urls')), # happening at the module level
    path('admin/', admin.site.urls),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cymbals/', views.index, name='index'),
  
    path('cymbals/<int:cymbal_id>/', views.details, name='details'),
    path('cymbal/create', views.CreateCymbals.as_view(), name='create_cymbals'),
    path('cymbal/<int:cymbal_id>/add_hire/', views.add_hire, name='add_hire'),
    path('cymbal/<int:pk>/delete/', views.CymbalDelete.as_view(), name='cymbal_delete'),
    path('cymbal/<int:pk>/update/', views.CymbalUpdate.as_view(), name='cymbal_update'),
    path('cymbal/<int:cymbal_id>/add_artist/<int:artist_id>/', views.add_artist, name='add_artist'),
    path('cymbal/<int:cymbal_id>/remove_artist/<int:artist_id>/', views.remove_artist, name='remove_artist'),

    path('artist/', views.IndexArtist.as_view(), name='index_artist'),
    path('artist/<int:pk>/detail/', views.Artists_Detail.as_view(), name='artists_detail'),
    path('artist/create', views.CreateArtist.as_view(), name='create_artist'),
    path('artist/<int:pk>/update/', views.UpdateArtist.as_view(), name='update_artist'),
    path('artist/<int:pk>/delete/', views.DeleteArtist.as_view(), name='delete_artist'),
   
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

EVENTS = (
    ('C', 'Clinic'),
    ('R', 'Recording'),
    ('G', 'Gig')
)

class Artist(models.Model):
    name = models.CharField(max_length=256)
    band = models.CharField(max_length=256)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('artists_detail', kwargs={'pk': self.id})


class Cymbal(models.Model):
    type = models.CharField(max_length=20)
    size = models.IntegerField()
    brand = models.CharField(max_length=20)
    description = models.TextField(max_length=256)
    series = models.CharField(max_length=20, default='')
    favoriteOf = models.CharField(max_length=256, blank=True)
    sold = models.BooleanField(default=False)
    artist = models.ManyToManyField(Artist)

    def get_absolute_url(self):
        return reverse('details', kwargs={'cymbal_id': self.id})

    def __self__(self):
        return f"{self.size} inch {self.brand} {self.type}"

class Hire(models.Model):
    date = models.DateField('Hire Date')
    event = models.CharField(max_length=1,
                             choices=EVENTS,
                             default=EVENTS[0][0]
                             )
    cymbal = models.ForeignKey(Cymbal, on_delete=models.CASCADE) # ensures if the parent is deleted related child are deleted
    # joins or references the cymbal model

    def __str__(self):
        return f"{self.get_event_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Hire

class HireForm(ModelForm):
    class Meta:
        model = Hire
        fields = ['date', 'event']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView 
from django.views.generic import DetailView, ListView
from .models import Cymbal, Artist
from .forms import HireForm
from django.urls import reverse

#Cymbal
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def index(request):
    cymbal = Cymbal.objects.all()
    return render(request, 'index.html', {
        'cymbal': cymbal
    })

def details(request, cymbal_id):
    cymbal = Cymbal.objects.get(id=cymbal_id)
    hire_form = HireForm()
    current_artist_ids = cymbal.artist.all().values_list('id')
    available_artist = Artist.objects.exclude(id__in=current_artist_ids)
    return render(request, 'details.html', { "cymbal": cymbal, 
                                            'hire_form': hire_form,
                                             'available_artist': available_artist,
                                              })


def add_hire(request, cymbal_id):
    hire_form = HireForm(request.POST)
    if hire_form.is_valid():
        new_hire = hire_form.save(commit=False)
        new_hire.cymbal_id = cymbal_id
        new_hire.save()
    return redirect('details', cymbal_id=cymbal_id)    

class CreateCymbals(CreateView):
    model = Cymbal
    fields = ['type', 'size', 'brand', 'description', 'series']
    
class CymbalDelete(DeleteView):
    model = Cymbal
    success_url = '/cymbals/'

class CymbalUpdate(UpdateView):
    model = Cymbal
    fields = ['size', 'description', 'brand', 'series']

#Artist
class IndexArtist(ListView):
    model = Artist

class CreateArtist(CreateView):
    model = Artist    
    fields = '__all__'

class Artists_Detail(DetailView):
    model = Artist    

class UpdateArtist(UpdateView):
    model = Artist
    fields = '__all__'

class DeleteArtist(DeleteView):
    model = Artist
    success_url = '/artist/'

def add_artist(request, cymbal_id, artist_id):
    Cymbal.objects.get(id=cymbal_id).artist.add(artist_id)
    return redirect('details', cymbal_id=cymbal_id)

def remove_artist(request, cymbal_id, artist_id):
    Cymbal.objects.get(id=cymbal_id).artist.remove(artist_id)
    return redirect('details', cymbal_id=cymbal_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About cymbals</h1>
<footer>All Rights Reserved, &copy; 2024 Cymbal Collector</footer>
{% endblock content %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Cymbal Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">Cymbal Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'create_cymbals' %}">Add a Cymbal</a></li>
          <li><a href="{% url 'index' %}">All Cymbals</a></li>
          <li><a href="{% url 'index_artist' %}">All Artists</a></li>
          <li><a href="{% url 'create_artist' %}">Add Artist</a></li>
        </ul>
      </div>
    </nav>
    </header>
  <main class="container">
    {% block content %} <!-- django template tags -->
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2024 Cymbal Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/details.html
{% extends 'base.html' %}
{% block content %}

<h1>Cymbal Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
     <div class="card-content">
      <span class="card-title">{{ cymbal.brand}} {{cymbal.type }}</span>
      <p>Series: {{ cymbal.series }}</p>
      <p>Size: {{ cymbal.size }} </p>
      <p>Description: {{ cymbal.description }}</p>
      <p>Used by: {{ cymbal.favoriteOf }}</p>
      {% if cybmal.sold == True %}
          <p>Sold</p>
      {% else %}
          <p>For Sale</p>
       {% endif %}   
  </div>
  <div class="card-action">
    <a href="{% url 'cymbal_update' cymbal.id %}">Edit Cymbal</a>
    <a href="{% url 'cymbal_delete' cymbal.id %}">Delete Cymbal</a>
    </div>
  </div>
</div>
<div class="col s6">
  <form action="{% url 'add_hire' cymbal.id %}" method="POST">
    {% csrf_token %}
    {{ hire_form.as_p }}
    <input type="submit" class="btn" value="Hire">
  </form>
    <br>
    {% if cymbal.hire_for_today %}
      <div class="card-panel teal-text center-align">{{ cymbal.brand }} {{ cymbal.type }} hired for the day!</div>
    {% else  %}
      <div class="card-panel red-text center-align">{{ cymbal.brand }} {{ cymbal.type }} available to hire!</div>  
    {% endif %}  
    <table class="stripped">
      <thread>
        <tr><th>Date</th><th>Event</th></tr>
      </thread>
      <tbody>
        {% for hire in cymbal.hire_set.all %}
          <tr>
            <td>{{ hire.date }}</td>
            <td>{{ hire.get_event_display }}</td>
          </tr>
        {% endfor %}  
      </tbody>
    </table>
</div>
</div>

<hr>

<div class="row">
    <div class="col s6">
        <h3>{{ cymbal.brand}} {{ cymbal.type }}</h3>
          {% if cymbal.artist.count %}
              {% for artist in cymbal.artist.all %}
                  <div class="card">
                    
                    <div class="card-content">
                      <span class="card-title">
                        
                       <span style="color:teal">{{ artist.name }} from {{ artist.band }} uses this {{ cymbal.brand}} {{ cymbal.type }}</span>
                      </span>
                      <form action="{% url 'remove_artist' cymbal.id artist.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn">Remove Artist</button>
                      </form>
                    </div>
                  </div>
                {% endfor %}  
              {% else %}
                <h4>No Artist uses this cymbal</h4>
              {% endif %}  
            </div>
            <div class="col s6">
              <h3>Available Artists</h3>
              {% if available_artist.all %}
              {% for a in available_artist.all %}
                <div class="card">
                  <div class="card-content">
                    <span>{{ a.name }} from {{ a.band }}</span>
                  </div>
                  <div class="card-action">
                    <form action="{% url 'add_artist' cymbal.id a.id %}" method="POST">
                      {% csrf_token %}
                      <button type="submit" class="btn">Add</button>
                    </form>
                  </div>
                </div>
                {% endfor %}
                {% else %}
                  <h5>{{ cymbal.brand }} {{ cymbal.type }} is that good all artist use this cymbal!</h5>
                {% endif %}
            </div>
          </div>
            
<script>
  const dateElement = document.getElementById('id_date');
  M.Datepicker.init(dateElement, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectElement = document.getElementById('id_event');
  M.FormSelect.init(selectElement);
  

</script>
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content%}

<h1>This is home!</h1>

{% endblock content %}

main_app/templates/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Cymbal List</h1>

{% for c in cymbal %}
<a href="{% url 'details' c.id %}"> 
    <div class="card">
            <div class="card-content">
                <span class=""card-title>{{ c.brand}} {{c.type }}</span>
                <p>Size: {{ c.size }} </p>
                <p>Description: {{ c.description }}</p>
                {% if c.sold == True %}
                    <p>Sold</p>
                {% else %}
                    <p>For Sale</p>
                 {% endif %}   
            </div>
    </div>
    {% endfor %}

    {% endblock %}

main_app/templates/main_app/artist_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete Artist</h1>

<h4>Are you sure you want to delete <span clas="teal-text">{{ object.name }}</span></h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'details' artist.id %}" class="btn">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/artist_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Artist Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
     <div class="card-content">
      <span class="card-title">{{ artist.name }} from {{ artist.band }}</span>
  </div>
  <div class="card-action">
    <a href="{% url 'update_artist' artist.id %}">Edit Artist</a>
    <a href="{% url 'delete_artist' artist.id %}">Delete Artist</a>
    </div>
  </div>
</div>

{% endblock %}

main_app/templates/main_app/artist_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{ object.name }} </span></h1>
    {% else %}
    <h1>Add Artist</h1>
    {% endif %}

    <form   method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        {% if object %}
        <input type="submit" value="Update Artist" class="btn">
        {% else %}
        <input type="submit" value="Create Artist" class="btn">
        {% endif %}
    </form>
{% endblock %}

main_app/templates/main_app/artist_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Artist List</h1>

{% for artist in artist_list %}
<a href="{% url 'artists_detail' artist.id %}"> 
    <div class="card">
            <div class="card-content">
                <span class=""card-title>{{ artist.name }} from {{ artist.band }}</span>
            </div>
    </div>
{% endfor %}
{% endblock %}

main_app/templates/main_app/cymbal_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete Cymbal</h1>

<h4>Are you sure you want to delete <span clas="teal-text">{{ object.name }}</span></h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'details' cymbal.id %}" class="btn">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/cymbal_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Cymbal Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
     <div class="card-content">
      <span class="card-title">{{ cymbal.brand}} {{cymbal.type }}</span>
      <p>Size: {{ cymbal.size }} </p>
      <p>Description: {{ cymbal.description }}</p>
      {% if cybmal.sold == True %}
          <p>Sold</p>
      {% else %}
          <p>For Sale</p>
       {% endif %}   
  </div>
  <div class="card-action">
    <a href="{% url 'cymbal_update' cymbal.id %}">Edit Cymbal</a>
    <a href="{% url 'cymbal_delete' cymbal.id %}">Delete Cymbal</a>
    </div>
  </div>
</div>
<div class="col s6">
  <form action="{% url 'add_hire' cymbal.id %}" method="POST">
    {% csrf_token %}
    {{ hire_form.as_p }}
    <input type="submit" class="btn" value="Hire">
  </form>
    <br>
    {% if cymbal.hire_for_today %}
      <div class="card-panel teal-text center-align">{{ cymbal.brand }} {{ cymbal.type }} hired for the day!</div>
    {% else  %}
      <div class="card-panel red-text center-align">{{ cymbal.brand }} {{ cymbal.type }} available to hire!</div>  
    {% endif %}  
    <table class="stripped">
      <thread>
        <tr><th>Date</th><th>Event</th></tr>
      </thread>
      <tbody>
        {% for hire in cymbal.hire_set.all %}
          <tr>
            <td>{{ hire.date }}</td>
            <td>{{ hire.get_event_display }}</td>
          </tr>
        {% endfor %}  
      </tbody>
    </table>
</div>
</div>

<script>
  const dateElement = document.getElementById('id_date');
  M.Datepicker.init(dateElement, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectElement = document.getElementById('id_event');
  M.FormSelect.init(selectElement);
  

</script>
{% endblock %}

main_app/templates/main_app/cymbal_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{ object.name }} </span></h1>
    {% else %}
    <h1>Add Cymbal</h1>
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        {% if object %}
        <input type="submit" value="Update Cymbal" class="btn">
        {% else %}
        <input type="submit" value="Create Cymbal" class="btn">
        {% endif %}
    </form>
{% endblock %}